name: Free Threading Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: 3.13t
          enable-cache: false
      - name: Set up Python
        run: uv python install
      - name: Install Dependencies
        run: |
          uv pip install numpy scipy pytest-timeout pytest-durations pytest-run-parallel
      - name: Build
        run: |
          uv pip install -v .
      - name: Run Tests
        run: |
          set -xe
          uv run --no-project python -m pytest --parallel-threads=2 --iterations=2 -v -s --timeout=600 --durations=10 -m "not thread_unsafe"
